# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 7807f280476d250747df63e1442808aa85e96d60bc2a8ef96173b9566af580add6f5e5d039a9da273eaef37843574df89c727e59f82f548ddab02a2dfae6632f

test:
  secret_key_base: b3280cc08041b9b042538e089cf81c0af1c08b8332ceca4975329796548ba5322e8a92f067a72764ce9dac8b0b96820644cf1abb83b76a83abece1b03d36b8a0

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
